Preference
mercadopago/sdk-go pull request #4
Opened 2024-01-29 17:39 UTC by brunacamposxx

Preference implementation, unit tests, integration tests and use example.

2024-02-14 16:51 UTC, eltinMeli requested changes

2024-02-14 16:51 UTC, eltinMeli commented on examples/apis/preference/update/main.go
> +	pref, err := client.Create(context.Background(), request)
```suggestion
	client := preference.NewClient(cfg)
	preference, err := client.Create(context.Background(), request)
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/client.go
> +	urlPreferenceWithParam = urlBase + "/preferences/{id}"
```suggestion
	urlBase       = "https://api.mercadopago.com/checkout/preferences"
	urlSearch    = urlBase + "/search"
	urlWithID    = urlBase + "/{id}"
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/request.go
> +	CurrencyID  string  `json:"currency_id,omitempty"`
Organizar tipos

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/request.go
> +	DateCreated    *time.Time             `json:"date_created,omitempty"`
Organizar por tipos e separar os tipos primitivos.
Remover os ponteiros
```suggestion
	Name           string                 `json:"name,omitempty"`
	Surname        string                 `json:"surname,omitempty"`
	Email          string                 `json:"email,omitempty"`
	
	DateCreated    *time.Time             `json:"date_created,omitempty"`
	Phone          PhoneRequest          `json:"phone,omitempty"`
	Identification IdentificationRequest `json:"identification,omitempty"`
	Address        AddressRequest        `json:"address,omitempty"`
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/request.go
> +	DefaultInstallments    int                              `json:"default_installments,omitempty"`
```suggestion
	ExcludedPaymentMethods []PreferencePaymentMethodRequest `json:"excluded_payment_methods,omitempty"`
	Installments           int                              `json:"installments,omitempty"`
	DefaultInstallments    int                              `json:"default_installments,omitempty"`
	
	ExcludedPaymentTypes   []PreferencePaymentTypeRequest   `json:"excluded_payment_types,omitempty"`
	DefaultPaymentMethodID string                           `json:"default_payment_method_id,omitempty"`
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/request.go
> +	ExpressShipment       bool                              `json:"express_shipment,omitempty"`
Organizar, separar os tipos e remover ponteiros

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/request.go
> +	Values *PreferenceTrackValuesRequest `json:"values,omitempty"`
```suggestion
	Type   string                        `json:"type,omitempty"`
	
	Values PreferenceTrackValuesRequest `json:"values,omitempty"`
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +	BackUrls            PreferenceBackUrls            `json:"back_urls"`
```suggestion
	BackURLS            PreferenceBackUrls            `json:"back_urls"`
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +type Response struct {
Organizar, separar os tipos e remover ponteiros

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +type PreferenceItem struct {
Organizar

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +type PreferencePayer struct {
Organizar, separar os tipos e remover ponteiros

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +type PreferencePaymentMethods struct {
Organizar e separar os tipos primitivos

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +type PreferenceShipments struct {
Organizar, separar os tipos e remover ponteiros

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/search_response.go
> +type SearchResponse struct {
Organizar os tipos
Creio que poderia manter no mesmo arquivo que tem os outros responses

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/search_response.go
> +type SearchResponsePage struct {
```suggestion
// SearchPageResponse is a search page that contains elements.
type SearchPageResponse struct {
```

2024-02-14 16:51 UTC, eltinMeli commented on pkg/preference/response.go
> +package preference
Tem algumas structs sem sufixo Response

2024-02-14 18:07 UTC, edmarSoaress commented on examples/apis/preference/search/main.go
> +	fmt.Println(pref)
@Eltin, o search não é uma lista, é um objeto que encapsula a lista e outros campos, assim como é é payment, portanto não faz sentido o for

2024-02-14 18:11 UTC, edmarSoaress commented on examples/apis/preference/create/main.go
> +}
@eltinMeli no exemplo de update não podemos definir o nome dessa variável como "preference" porque da conflito com a linha que constrói o request body do update ( preferenceRequest := preference.Request ). isso pq  o nome do pkg é o mesmo da variável

2024-02-14 18:14 UTC, edmarSoaress commented on pkg/preference/request.go
> +	ExpressShipment       bool                              `json:"express_shipment,omitempty"`
o ponteiro no request deve permanecer, isso evita de serializar valores default , foi definido não usar apenas no response

2024-02-16 20:59 UTC, eltinMeli commented on pkg/preference/request.go
> +	Expires             *bool                  `json:"expires,omitempty"`
Pq ponteiro no bool?

2024-02-16 21:00 UTC, rhames07 approved these changes

2024-02-16 21:07 UTC, edmarSoaress commented on pkg/preference/request.go
> +	Expires             *bool                  `json:"expires,omitempty"`
boa pergunta, talvez a Bruna tenha colocado pq em Java tava como Boolean, então teria tres possíveis valores: null, true ou false. Vou remover

2024-02-19 17:50 UTC, eltinMeli approved these changes

2024-02-19 17:56 UTC, merged