Feature/card token
mercadopago/sdk-go pull request #7
Opened 2024-02-08 13:58 UTC by meliguilhermefernandes

Card Token implementation, unit tests, integration tests and use example.

2024-02-08 17:21 UTC, edmarSoaress commented
Não vamos ter testes de integração para esse client?

2024-02-08 17:29 UTC, meliguilhermefernandes commented
> Não vamos ter testes de integração para esse client? @meliguilhermefernandes

Não me atentei aos testes de integração, já adiciono!

2024-02-08 18:35 UTC, eltinMeli requested changes

2024-02-08 18:35 UTC, eltinMeli commented on pkg/cardtoken/client.go
> +	Get(ctx context.Context, id string) (*Response, error)
Não será deprecado?

2024-02-08 18:35 UTC, eltinMeli commented on pkg/cardtoken/response.go
> +	Id                 string     `json:"id"`
```suggestion
	ID                 string     `json:"id"`
```

2024-02-08 18:35 UTC, eltinMeli commented on pkg/cardtoken/response.go
> +	DateDue            time.Time  `json:"date_due"`
```suggestion
	DateCreated        *time.Time  `json:"date_created"`
	DateLastUpdated    *time.Time  `json:"date_last_updated"`
	DateDue            *time.Time  `json:"date_due"`
```

2024-02-08 19:19 UTC, meliguilhermefernandes commented on pkg/cardtoken/client.go
> +	urlPost = baseURL + "/v1/card_tokens"
Como o GET foi removido ficou:
url = "https://api.mercadopago.com/v1/card_tokens"

2024-02-08 19:20 UTC, meliguilhermefernandes commented on pkg/cardtoken/response.go
> +	Id                 string     `json:"id"`
Ajustado!!

2024-02-08 19:21 UTC, edmarSoaress commented on pkg/cardtoken/request.go
> +	SiteId          string     `json:"site_id"`
```suggestion
	SiteID          string     `json:"site_id"`
```

2024-02-08 19:21 UTC, edmarSoaress commented on pkg/cardtoken/client.go
> +type Client interface {
Para seguir o padrão dos demais clients
```suggestion
// Client contains the method to interact with the card token API.
type Client interface {
```

2024-02-08 19:22 UTC, meliguilhermefernandes commented on pkg/cardtoken/response.go
> +	DateDue            time.Time  `json:"date_due"`
Ajustado!!

2024-02-08 19:23 UTC, meliguilhermefernandes commented on pkg/cardtoken/client.go
> +	Get(ctx context.Context, id string) (*Response, error)
Removido!!

2024-02-08 19:34 UTC, meliguilhermefernandes commented on examples/apis/cardtoken/create/main.go
> +	result, err := client.Create(context.Background(), cardtoken.Request{})
Ajustado!!

2024-02-08 19:34 UTC, meliguilhermefernandes commented on examples/apis/cardtoken/get/main.go
> +	result, err := client.Get(context.Background(), "123")
GET foi removido!!

2024-02-08 19:36 UTC, meliguilhermefernandes commented on pkg/cardtoken/client.go
> +		return nil, fmt.Errorf("error create card token: %w", err)
Ajustado!!

2024-02-08 19:39 UTC, meliguilhermefernandes commented on pkg/cardtoken/request.go
> +	Cardholder      Cardholder `json:"cardholder"`
Ajustado!!

2024-02-08 19:40 UTC, meliguilhermefernandes commented on pkg/cardtoken/request.go
> +	Identification Identification `json:"identification"`
Ajustado!!

2024-02-08 19:40 UTC, meliguilhermefernandes commented on pkg/cardtoken/request.go
> +	SiteId          string     `json:"site_id"`
Ajustado!!

2024-02-08 19:43 UTC, meliguilhermefernandes commented on pkg/cardtoken/client.go
> +type Client interface {
Ajustado!!

2024-02-08 19:43 UTC, meliguilhermefernandes commented on pkg/cardtoken/client.go
> +	Create(ctx context.Context, request Request) (*Response, error)
Ajustado!!

2024-02-08 20:44 UTC, edmarSoaress commented on pkg/cardtoken/response.go
> +	Cardholder         *Cardholder `json:"cardholder"`
Só vamos utilizar ponteiro pra datas no response. Pra struct só vamos utilizar ponteiro nas struct de request
```suggestion
	Cardholder         Cardholder `json:"cardholder"`
```

2024-02-08 20:44 UTC, edmarSoaress commented on examples/apis/cardtoken/get/main.go
Precisa remover esse exemplo, porque não temos mais o get no client

2024-02-08 20:48 UTC, edmarSoaress commented on pkg/cardtoken/client_test.go
> +func Test_parseDate(t *testing.T) {
Qual a necessidade desse teste? está apenas testando uma função que é usada pra mockar uma data

2024-02-08 21:06 UTC, meliguilhermefernandes commented on pkg/cardtoken/response.go
> +	Cardholder         *Cardholder `json:"cardholder"`
Ajustado!!

2024-02-08 21:06 UTC, meliguilhermefernandes commented on pkg/cardtoken/client_test.go
> +func Test_parseDate(t *testing.T) {
Ajustado!!

2024-02-08 21:12 UTC, lucmantovani commented on go.mod
> +	github.com/stretchr/testify v1.8.4
Onde é usado?

2024-02-08 21:24 UTC, meliguilhermefernandes commented on go.mod
> +	github.com/stretchr/testify v1.8.4
Sobrou o importe de uma func que não será mais usada, Removido!!

2024-02-08 21:41 UTC, eltinMeli commented on pkg/cardtoken/client.go
> +)
```suggestion
const url = "https://api.mercadopago.com/v1/card_tokens"
```

2024-02-08 21:41 UTC, eltinMeli commented on examples/apis/cardtoken/create/main.go
> +		SiteID:          "{{SiteID}}",
{{SITE_ID}}

2024-02-09 10:50 UTC, meliguilhermefernandes commented on examples/apis/cardtoken/get/main.go
Removido!!

2024-02-09 12:08 UTC, edmarSoaress approved these changes

2024-02-09 12:57 UTC, eltinMeli approved these changes

2024-02-09 13:07 UTC, lucmantovani approved these changes

2024-02-09 13:11 UTC, merged